// processLineCommand + sendMorningSummary 修正パッチ
var fs = require('fs');

var serverFile = '/home/ubuntu/kabeuchi-system/src/server.js';
var server = fs.readFileSync(serverFile, 'utf8');

// 1. processLineCommand 置換
var cmdStart = 'async function processLineCommand(text, userId) {';
var cmdEnd = '\n\n// LINE返信';
var cmdStartIdx = server.indexOf(cmdStart);
var cmdEndIdx = server.indexOf(cmdEnd, cmdStartIdx);

// 「優先度設定」がまだ追加されてなければ置換
if (cmdStartIdx >= 0 && cmdEndIdx >= 0 && server.indexOf('優先度設定') === -1) {
  var newCmd = '';
  newCmd += 'async function processLineCommand(text, userId) {\n';
  newCmd += '  var t = text.trim();\n';
  newCmd += '\n';
  newCmd += '  // 承認\n';
  newCmd += '  if (t === \'承認\' || t === \'OK\' || t === \'ok\') {\n';
  newCmd += '    var latest = db.prepare("SELECT * FROM sessions WHERE status = \'active\' ORDER BY priority ASC, updated_at DESC LIMIT 1").get();\n';
  newCmd += '    if (latest) {\n';
  newCmd += '      db.prepare(\'INSERT INTO decisions (session_id, decision) VALUES (?,?)\').run(latest.id, \'approved\');\n';
  newCmd += '      return \'承認しました（セッション: \' + latest.title + \'）\';\n';
  newCmd += '    }\n';
  newCmd += '    return \'アクティブなセッションがありません\';\n';
  newCmd += '  }\n';
  newCmd += '\n';
  newCmd += '  // 却下\n';
  newCmd += '  if (t.startsWith(\'却下\') || t.startsWith(\'NG\')) {\n';
  newCmd += '    var comment = t.replace(/^(却下|NG)\\s*/, \'\');\n';
  newCmd += '    var latest2 = db.prepare("SELECT * FROM sessions WHERE status = \'active\' ORDER BY priority ASC, updated_at DESC LIMIT 1").get();\n';
  newCmd += '    if (latest2) {\n';
  newCmd += '      db.prepare(\'INSERT INTO decisions (session_id, decision, comment) VALUES (?,?,?)\').run(latest2.id, \'rejected\', comment || null);\n';
  newCmd += '      return \'却下しました\' + (comment ? \'（理由: \' + comment + \'）\' : \'\');\n';
  newCmd += '    }\n';
  newCmd += '    return \'アクティブなセッションがありません\';\n';
  newCmd += '  }\n';
  newCmd += '\n';
  newCmd += '  // プロジェクト一覧（Feature 1）\n';
  newCmd += '  if (t === \'一覧\' || t === \'リスト\' || t === \'プロジェクト\') {\n';
  newCmd += '    var all = db.prepare("SELECT * FROM sessions WHERE status IN (\'active\',\'sleep\') ORDER BY priority ASC, updated_at DESC").all();\n';
  newCmd += '    if (all.length === 0) return \'アクティブなプロジェクトなし\';\n';
  newCmd += '    return \'プロジェクト一覧\\n\\n\' + all.map(function(s) {\n';
  newCmd += '      var pri = s.priority || 5;\n';
  newCmd += '      var star = pri <= 3 ? \'[優先\' + pri + \'] \' : \'\';\n';
  newCmd += '      var dl = s.deadline ? \' 〆\' + s.deadline : \'\';\n';
  newCmd += '      return star + s.title + \' → Phase\' + s.phase + \' Step\' + s.current_round + \' (\' + s.status + \')\' + dl;\n';
  newCmd += '    }).join(\'\\n\');\n';
  newCmd += '  }\n';
  newCmd += '\n';
  newCmd += '  // 状態確認（優先度付き）\n';
  newCmd += '  if (t === \'状態\' || t === \'ステータス\') {\n';
  newCmd += '    var sessions = db.prepare("SELECT * FROM sessions WHERE status = \'active\' ORDER BY priority ASC, updated_at DESC LIMIT 5").all();\n';
  newCmd += '    if (sessions.length === 0) return \'アクティブなセッションなし\';\n';
  newCmd += '    return sessions.map(function(s) {\n';
  newCmd += '      var pri = s.priority || 5;\n';
  newCmd += '      var star = pri <= 3 ? \'[優先\' + pri + \'] \' : \'\';\n';
  newCmd += '      return star + \'[\' + s.id + \'] \' + s.title + \' (Phase\' + s.phase + \' Step\' + s.current_round + \')\';\n';
  newCmd += '    }).join(\'\\n\');\n';
  newCmd += '  }\n';
  newCmd += '\n';
  newCmd += '  // 優先度設定（Feature 3）: 「優先 セッションID 優先度」\n';
  newCmd += '  var priMatch = t.match(/^優先\\s+(\\d+)\\s+(\\d+)$/);\n';
  newCmd += '  if (priMatch) {\n';
  newCmd += '    var priSid = parseInt(priMatch[1]);\n';
  newCmd += '    var priVal = parseInt(priMatch[2]);\n';
  newCmd += '    db.prepare(\'UPDATE sessions SET priority = ? WHERE id = ?\').run(priVal, priSid);\n';
  newCmd += '    return \'セッション\' + priSid + \'の優先度を\' + priVal + \'に設定しました\';\n';
  newCmd += '  }\n';
  newCmd += '\n';
  newCmd += '  // 最優先設定（Feature 3）: 「〇〇を最優先」\n';
  newCmd += '  var topPriMatch = t.match(/(.+)(を最優先|を優先|最優先にして)/);\n';
  newCmd += '  if (topPriMatch) {\n';
  newCmd += '    var keyword = topPriMatch[1].trim();\n';
  newCmd += '    var found = db.prepare("SELECT * FROM sessions WHERE title LIKE ? AND status = \'active\' LIMIT 1").get(\'%\' + keyword + \'%\');\n';
  newCmd += '    if (found) {\n';
  newCmd += '      db.prepare(\'UPDATE sessions SET priority = 1 WHERE id = ?\').run(found.id);\n';
  newCmd += '      return \'「\' + found.title + \'」を最優先(1)に設定しました\';\n';
  newCmd += '    }\n';
  newCmd += '    return \'「\' + keyword + \'」に該当するセッションが見つかりません\';\n';
  newCmd += '  }\n';
  newCmd += '\n';
  newCmd += '  // 締め切り設定（Feature 3）: 「〇〇は来週」「〇〇は急がない」\n';
  newCmd += '  var deadlineMatch = t.match(/(.+)(は来週|は今月中|は急がない)/);\n';
  newCmd += '  if (deadlineMatch) {\n';
  newCmd += '    var dKeyword = deadlineMatch[1].trim();\n';
  newCmd += '    var dFound = db.prepare("SELECT * FROM sessions WHERE title LIKE ? AND status = \'active\' LIMIT 1").get(\'%\' + dKeyword + \'%\');\n';
  newCmd += '    if (dFound) {\n';
  newCmd += '      if (t.indexOf(\'来週\') >= 0) {\n';
  newCmd += '        var nextWeek = new Date(Date.now() + 7 * 86400000);\n';
  newCmd += '        var dl = nextWeek.toISOString().split(\'T\')[0];\n';
  newCmd += '        db.prepare(\'UPDATE sessions SET deadline = ? WHERE id = ?\').run(dl, dFound.id);\n';
  newCmd += '        return \'「\' + dFound.title + \'」の期限を\' + dl + \'に設定しました\';\n';
  newCmd += '      } else if (t.indexOf(\'今月中\') >= 0) {\n';
  newCmd += '        var now = new Date();\n';
  newCmd += '        var eom = now.getFullYear() + \'-\' + String(now.getMonth() + 1).padStart(2, \'0\') + \'-\' + new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();\n';
  newCmd += '        db.prepare(\'UPDATE sessions SET deadline = ? WHERE id = ?\').run(eom, dFound.id);\n';
  newCmd += '        return \'「\' + dFound.title + \'」の期限を\' + eom + \'に設定しました\';\n';
  newCmd += '      } else if (t.indexOf(\'急がない\') >= 0) {\n';
  newCmd += '        db.prepare(\'UPDATE sessions SET priority = 8 WHERE id = ?\').run(dFound.id);\n';
  newCmd += '        return \'「\' + dFound.title + \'」の優先度を下げました(8)\';\n';
  newCmd += '      }\n';
  newCmd += '    }\n';
  newCmd += '  }\n';
  newCmd += '\n';
  newCmd += '  // フェーズ承認（Feature 2）: 「フェーズ1承認」\n';
  newCmd += '  var phaseApproveMatch = t.match(/フェーズ(\\d+)(承認|OK|進めて)/i);\n';
  newCmd += '  if (phaseApproveMatch) {\n';
  newCmd += '    var paSidMatch = t.match(/セッション(\\d+)/);\n';
  newCmd += '    var paSid = paSidMatch ? parseInt(paSidMatch[1]) : null;\n';
  newCmd += '    var paPhase = parseInt(phaseApproveMatch[1]);\n';
  newCmd += '    var paSession = paSid\n';
  newCmd += '      ? db.prepare(\'SELECT * FROM sessions WHERE id = ?\').get(paSid)\n';
  newCmd += '      : db.prepare("SELECT * FROM sessions WHERE status = \'active\' ORDER BY updated_at DESC LIMIT 1").get();\n';
  newCmd += '    if (paSession) {\n';
  newCmd += '      var nextPhase = paPhase + 1;\n';
  newCmd += '      db.prepare(\'UPDATE sessions SET phase = ?, current_round = 0 WHERE id = ?\').run(nextPhase, paSession.id);\n';
  newCmd += '      db.prepare(\'INSERT INTO decisions (session_id, decision, comment) VALUES (?,?,?)\').run(paSession.id, \'approved\', \'Phase\' + paPhase + \'承認→Phase\' + nextPhase + \'開始\');\n';
  newCmd += '      return \'「\' + paSession.title + \'」Phase\' + paPhase + \'承認。Phase\' + nextPhase + \'に進みます。\';\n';
  newCmd += '    }\n';
  newCmd += '    return \'セッションが見つかりません\';\n';
  newCmd += '  }\n';
  newCmd += '\n';
  newCmd += '  // ステップやり直し（Feature 2）: 「ステップ3やり直し」\n';
  newCmd += '  var stepRedoMatch = t.match(/ステップ(\\d+)(やり直し|再実行|リトライ)/);\n';
  newCmd += '  if (stepRedoMatch) {\n';
  newCmd += '    var srSidMatch = t.match(/セッション(\\d+)/);\n';
  newCmd += '    var srSid = srSidMatch ? parseInt(srSidMatch[1]) : null;\n';
  newCmd += '    var srStep = parseInt(stepRedoMatch[1]);\n';
  newCmd += '    var srSession = srSid\n';
  newCmd += '      ? db.prepare(\'SELECT * FROM sessions WHERE id = ?\').get(srSid)\n';
  newCmd += '      : db.prepare("SELECT * FROM sessions WHERE status = \'active\' ORDER BY updated_at DESC LIMIT 1").get();\n';
  newCmd += '    if (srSession) {\n';
  newCmd += '      engine.clearStep(srSession.id, srStep);\n';
  newCmd += '      return \'「\' + srSession.title + \'」のStep\' + srStep + \'をクリアしました。再実行します。\';\n';
  newCmd += '    }\n';
  newCmd += '    return \'セッションが見つかりません\';\n';
  newCmd += '  }\n';
  newCmd += '\n';
  newCmd += '  // パターン採用（Feature 2）: 「パターンA採用」\n';
  newCmd += '  var patternMatch = t.match(/パターン([A-Da-d])(採用|承認|で決定|にして)/);\n';
  newCmd += '  if (patternMatch) {\n';
  newCmd += '    var pat = patternMatch[1].toUpperCase();\n';
  newCmd += '    var latestQueue = db.prepare("SELECT * FROM output_queue WHERE status = \'awaiting_approval\' ORDER BY created_at DESC LIMIT 1").get();\n';
  newCmd += '    if (latestQueue) {\n';
  newCmd += '      var caseId = outputGen.approveOutput(latestQueue.id, pat);\n';
  newCmd += '      return \'パターン\' + pat + \'を採用しました（case_library ID: \' + caseId + \'）\';\n';
  newCmd += '    }\n';
  newCmd += '    return \'承認待ちのアウトプットがありません\';\n';
  newCmd += '  }\n';
  newCmd += '\n';
  newCmd += '  // 競合追加（Feature 7）: 「競合追加 URL」\n';
  newCmd += '  var compMatch = t.match(/^競合追加\\s+(.+)/);\n';
  newCmd += '  if (compMatch) {\n';
  newCmd += '    var compUrl = compMatch[1].trim();\n';
  newCmd += '    var compName = compUrl.replace(/https?:\\/\\//, \'\').split(\'/\')[0];\n';
  newCmd += '    db.prepare(\'INSERT INTO competitors (name, url) VALUES (?,?)\').run(compName, compUrl);\n';
  newCmd += '    return \'競合「\' + compName + \'」を登録しました。週次で自動チェックします。\';\n';
  newCmd += '  }\n';
  newCmd += '\n';
  newCmd += '  // 保留中の質問があれば回答として処理\n';
  newCmd += '  var pending = lineQA.getPendingQuestion();\n';
  newCmd += '  if (pending) {\n';
  newCmd += '    lineQA.resolveAnswer(pending.id, t);\n';
  newCmd += '    return \'回答受付しました。処理を再開します。\\n\\nQ: \' + pending.question.substring(0, 80) + \'\\nA: \' + t;\n';
  newCmd += '  }\n';
  newCmd += '\n';
  newCmd += '  // スマートQ&A（Claudeがプロジェクト参照して回答）\n';
  newCmd += '  try {\n';
  newCmd += '    console.log(\'[Smart QA] 質問処理開始: \' + t.substring(0, 50));\n';
  newCmd += '    var answer = await lineQA.handleSmartQA(t, userId);\n';
  newCmd += '    return answer;\n';
  newCmd += '  } catch (err) {\n';
  newCmd += '    console.error(\'[Smart QA Error]\', err.message);\n';
  newCmd += '    db.prepare(\'INSERT INTO voice_memos (text) VALUES (?)\').run(t);\n';
  newCmd += '    return \'メモ保存しました: 「\' + t.substring(0, 30) + \'...」\';\n';
  newCmd += '  }\n';
  newCmd += '}';

  server = server.substring(0, cmdStartIdx) + newCmd + server.substring(cmdEndIdx);
  console.log('[server] processLineCommand 更新完了');
} else {
  console.log('[server] processLineCommand スキップ (既に適用済みまたは位置不一致)');
}

// 2. sendMorningSummary 置換
var morningStart = 'async function sendMorningSummary() {';
var morningEnd = '\n\n// ============================================\n// 週次レポート（月曜7時）';
var morningStartIdx = server.indexOf(morningStart);
var morningEndIdx = server.indexOf(morningEnd, morningStartIdx);

// 「プロジェクト進捗一覧」がまだなければ置換
if (morningStartIdx >= 0 && morningEndIdx >= 0 && server.indexOf('プロジェクト進捗一覧') === -1) {
  var newMorning = '';
  newMorning += 'async function sendMorningSummary() {\n';
  newMorning += '  console.log(\'[朝サマリー] 生成開始\');\n';
  newMorning += '  var anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });\n';
  newMorning += '  var msg = \'おはようございます、前田さん\\n\';\n';
  newMorning += '\n';
  newMorning += '  // 就寝中に処理したセッション結果\n';
  newMorning += '  if (global._sleepResults && global._sleepResults.length > 0) {\n';
  newMorning += '    msg += \'\\n【就寝中の処理結果: \' + global._sleepResults.length + \'件】\\n\';\n';
  newMorning += '    global._sleepResults.forEach(function(r) {\n';
  newMorning += '      msg += \'・\' + r.title + \' → \' + r.status + \'\\n\';\n';
  newMorning += '    });\n';
  newMorning += '    var sleepLogs = db.prepare("SELECT * FROM discussion_logs WHERE is_sleep_mode = 1 AND created_at > datetime(\'now\', \'-12 hours\') ORDER BY session_id, created_at ASC").all();\n';
  newMorning += '    if (sleepLogs.length > 0) {\n';
  newMorning += '      var logText = sleepLogs.map(function(l) { return \'[S\' + l.session_id + \' \' + l.role_label + \'] \' + l.content.substring(0, 200); }).join(\'\\n---\\n\');\n';
  newMorning += '      try {\n';
  newMorning += '        var r = await anthropic.messages.create({\n';
  newMorning += '          model: \'claude-sonnet-4-20250514\', max_tokens: 2000,\n';
  newMorning += '          system: \'就寝中に複数プロジェクトが並列処理されました。各プロジェクトの進捗・重要ポイントを簡潔にまとめてください。\',\n';
  newMorning += '          messages: [{ role: \'user\', content: logText.substring(0, 10000) }]\n';
  newMorning += '        });\n';
  newMorning += '        msg += \'\\n\' + r.content[0].text;\n';
  newMorning += '      } catch(e) { console.error(\'[朝サマリー] 要約エラー:\', e.message); }\n';
  newMorning += '    }\n';
  newMorning += '    global._sleepResults = null;\n';
  newMorning += '  } else if (global._sleepBizIdeas) {\n';
  newMorning += '    try {\n';
  newMorning += '      var r2 = await anthropic.messages.create({\n';
  newMorning += '        model: \'claude-sonnet-4-20250514\', max_tokens: 2000,\n';
  newMorning += '        system: \'新規事業アイデア分析をLINE通知用に簡潔にまとめてください。各案のタイトル、市場規模、3年後の営業利益を箇条書きで。推奨案を明示。\',\n';
  newMorning += '        messages: [{ role: \'user\', content: global._sleepBizIdeas.text + \'\\n\\nHTML URL: \' + global._sleepBizIdeas.htmlUrl }]\n';
  newMorning += '      });\n';
  newMorning += '      msg += \'\\n【新規事業アイデア（自動調査）】\\n\\n\' + r2.content[0].text;\n';
  newMorning += '      msg += \'\\n\\n詳細はこちら:\\n\' + global._sleepBizIdeas.htmlUrl;\n';
  newMorning += '      global._sleepBizIdeas = null;\n';
  newMorning += '    } catch(e) { console.error(\'[朝サマリー] 新規事業要約エラー:\', e.message); }\n';
  newMorning += '  } else {\n';
  newMorning += '    console.log(\'[朝サマリー] 就寝中ログも新規事業アイデアもなし\');\n';
  newMorning += '    return;\n';
  newMorning += '  }\n';
  newMorning += '\n';
  newMorning += '  // 全セッション進捗サマリー（Feature 1/3/4）\n';
  newMorning += '  var allSess = db.prepare("SELECT * FROM sessions WHERE status IN (\'active\',\'sleep\') ORDER BY priority ASC").all();\n';
  newMorning += '  if (allSess.length > 0) {\n';
  newMorning += '    msg += \'\\n\\n【プロジェクト進捗一覧】\\n\';\n';
  newMorning += '    allSess.forEach(function(s) {\n';
  newMorning += '      var pri = s.priority || 5;\n';
  newMorning += '      var star = pri <= 3 ? \'[優先\' + pri + \'] \' : \'\';\n';
  newMorning += '      var dl = s.deadline ? \' 〆\' + s.deadline : \'\';\n';
  newMorning += '      msg += star + s.title + \' → Phase\' + s.phase + \' Step\' + s.current_round + dl + \'\\n\';\n';
  newMorning += '    });\n';
  newMorning += '  }\n';
  newMorning += '\n';
  newMorning += '  // 未承認アウトプットキュー\n';
  newMorning += '  var pendingOut = db.prepare("SELECT * FROM output_queue WHERE status = \'awaiting_approval\'").all();\n';
  newMorning += '  if (pendingOut.length > 0) {\n';
  newMorning += '    msg += \'\\n【承認待ちアウトプット: \' + pendingOut.length + \'件】\\n\' +\n';
  newMorning += '      pendingOut.map(function(p) { return \'・\' + p.output_type + \'（推奨: パターン\' + p.recommended_pattern + \'）\'; }).join(\'\\n\') +\n';
  newMorning += '      \'\\n→ 「承認」「パターンA採用」「却下 理由」で返信\';\n';
  newMorning += '  }\n';
  newMorning += '\n';
  newMorning += '  await sendLine(msg);\n';
  newMorning += '  console.log(\'[朝サマリー] 送信完了\');\n';
  newMorning += '}';

  server = server.substring(0, morningStartIdx) + newMorning + server.substring(morningEndIdx);
  console.log('[server] sendMorningSummary 更新完了');
} else {
  console.log('[server] sendMorningSummary スキップ');
}

fs.writeFileSync(serverFile, server, 'utf8');
console.log('patch_7features_fix.js 適用完了');
